### ISSUE TITLE
support for the 1 version scheme (latest release)

### ISSUE THREAD

**Issue by tpapp** [tpapp/texlive-julia-minimal-docker#23]
cf KristofferC/PGFPlotsX.jl#241

**Comment by tpapp** [comment]
@KristofferC, @fredrikekre: is there an URL scheme for getting the latest minor release, or does that need to be updated manually?

**Comment by KristofferC** [comment]
I think until we have something like https://github.com/JuliaLang/julia/issues/33817 it has to be done manually.

**Comment by fredrikekre** [comment]
Can atleast do something like https://github.com/tpapp/texlive-julia-minimal-docker/pull/24 for now.
